version: '3'
services:
  # app images and dependencies
  app:
    build:
      context: app/
      dockerfile: Dockerfile
    hostname: app
    # command: ./create-app.sh
    command: gunicorn --bind :${PORT:-5000} --certfile certificate.crt --keyfile private.key --workers 2 --threads 8 --timeout 0 "app:create_app('${FLASK_CONFIG:-development}')"
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - cloud-sql-proxy
    env_file:
      - .env
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    command: /cloud_sql_proxy -instances=eighth-vehicle-287322:us-central1:datab=tcp:0.0.0.0:3306 -credential_file=/config
    volumes:
    - ./app/keys/cloud_sql_proxy_key.json:/config
    ports:
    - 3306:3306
  db:
    image: mysql:5.7
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testing
  redis: 
    image: redis:latest

  # Worker images and dependencies
  worker:
    build:
      context: task-worker/
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - standalone-chrome
  standalone-chrome:
    hostname: selenium
    ports:
      - '4444:4444'
      - '5900:5900'
    volumes:
      - '/dev/shm:/dev/shm'
    image: 'selenium/standalone-chrome-debug:latest'


  # hub:
  #   image: selenium/hub:latest
  #   expose:
  #     - 4444
  # chrome:
  #   image: selenium/node-chrome-debug:latest
  #   environment:
  #     - HUB_PORT_4444_TCP_ADDR=hub
  #     - HUB_PORT_4444_TCP_PORT=4444
  #   ports:
  #     - 5900:5900
  #   depends_on:
  #     - hub