version: '3'
services:
  app:
    build:
      context: app/
      dockerfile: Dockerfile
    hostname: app
    ports:
      - "5000:5000"
    depends_on:
    - cloud-sql-proxy
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    command: /cloud_sql_proxy -instances=eighth-vehicle-287322:us-central1:datab=tcp:0.0.0.0:3306 -credential_file=/config
    volumes:
    - ./app/keys/cloud_sql_proxy_key.json:/config
    ports:
    - 3306:3306
  hub:
    image: selenium/hub:latest
    expose:
      - 4444
  chrome:
    image: selenium/node-chrome-debug:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub