service: task-service
runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 1
  target_concurrent_requests: 1
