apiVersion: v1
kind: Service
metadata:
  labels:
    app: csp
  name: csp
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: csp
status:
  loadBalancer: {}