version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    command: ./create-app.sh
    env_file: 
      - app.env
    ports:
      - "8080:8080"
    depends_on:
    - db
  db:
    image: mysql:5.7
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testing
  redis:
    image: redis:latest
    hostname: redis
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    command: ./celery-worker.sh
    env_file: 
      - app.env
    depends_on:
    - db
    - redis
  
  # celery-cron:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   hostname: app
  #   command: ./celery-cron.sh
  #   env_file: 
  #     - app.env
  #   depends_on:
  #   - db
  #   - redis

  # rabbit:
  #   hostname: rabbit
  #   image: rabbitmq:latest
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=mypass
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # flower:
  #   image: mher/flower
  #   ports:
  #     - 5555:5555
  #   env_file: 
  #     - app.env
  #   #environment:
  #     #CELERY_BROKER_URL: 
  #     #CELERY_RESULT_BACKEND:
