version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    env_file: 
      - app.env
    ports:
      - "5000:5000"
    depends_on:
    - db
  redis:
    image: redis:latest
    hostname: redis
  db:
    image: mysql:5.7
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testing
  
  # rabbit:
  #   hostname: rabbit
  #   image: rabbitmq:latest
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=mypass
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # flower:
  #   image: mher/flower
  #   ports:
  #     - 5555:5555
  #   env_file: 
  #     - app.env
  #   #environment:
  #     #CELERY_BROKER_URL: 
  #     #CELERY_RESULT_BACKEND:
