apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  # creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: http
    port: 5000
    targetPort: web
  # - name: "8080"
  #   port: 8080
  #   targetPort: 8080
  selector:
    app: app
status:
  loadBalancer: {}
