apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app 
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              key: CELERY_BROKER_URL
              name: env
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              key: CELERY_RESULT_BACKEND
              name: env
        - name: CLIENT_SECRETS_FILE
          valueFrom:
            configMapKeyRef:
              key: CLIENT_SECRETS_FILE
              name: env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: env
        - name: FLASK_CONFIG
          valueFrom:
            configMapKeyRef:
              key: FLASK_CONFIG
              name: env
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: env
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: REDIS_URL
              name: env
        image: app:latest
        imagePullPolicy: "Never"
        command: 
          - './create-app.sh'
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "2Gi"
            cpu:    "500m"
          limits:
            memory: "2Gi"
            cpu: 500m
      - name: celery-worker
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              key: CELERY_BROKER_URL
              name: env
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              key: CELERY_RESULT_BACKEND
              name: env
        - name: CLIENT_SECRETS_FILE
          valueFrom:
            configMapKeyRef:
              key: CLIENT_SECRETS_FILE
              name: env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: env
        - name: FLASK_CONFIG
          valueFrom:
            configMapKeyRef:
              key: FLASK_CONFIG
              name: env
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: env
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: REDIS_URL
              name: env
        image: app:latest
        imagePullPolicy: "Never"
        command: 
          - './celery-worker.sh'
        resources:
          requests:
            memory: "1Gi"
            cpu:    "50m"
          limits:
            memory: "2Gi"
            cpu: 100m
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # # If connecting from a VPC-native GKE cluster, you can use the
          # # following flag to have the proxy connect over private IP
          # # - "-ip_address_types=PRIVATE"

          # # Replace DB_PORT with the port the proxy should listen on
          # # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=eighth-vehicle-287322:us-central1:datab=tcp:0.0.0.0:3306"
          - "-credential_file=/secrets/cloudsql/credentials.json"  #keys/cloud_sql_proxy_key.json"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: cloudsql
          mountPath: /cloudsql
        resources:
          requests:
            memory: "2Gi"
            cpu:    "500m"
          limits:
            memory: "2Gi"
            cpu: "500m"
      # - name: nginx-controller
      #   image: nginx:latest
      #   imagePullPolicy: "IfNotPresent"
      #   ports:
      #     - containerPort: 80
      #     - containerPort: 443
      #   volumeMounts:
      #     - name: nginx-config
      #       mountPath: /etc/nginx/nginx.conf
      #       subPath: nginx.conf
      #   resources: {}
      volumes: 
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: {}
      # - name: nginx-config
      #   configMap:
      #     name: nginx-conf
      hostname: app
      restartPolicy: Always
status: {}
