apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: standalone-chrome
  name: standalone-chrome
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  - name: "5900"
    port: 5900
    targetPort: 5900
  selector:
    io.kompose.service: standalone-chrome
status:
  loadBalancer: {}
