apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: standalone-chrome-claim
  name: standalone-chrome-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
