apiVersion: v1
kind: Service
metadata:
  labels:
    task-worker: standalone-chrome
  name: standalone-chrome
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  - name: "5900"
    port: 5900
    targetPort: 5900
  selector:
    task-worker: standalone-chrome
status:
  loadBalancer: {}
